author: Austin Clark
category: accounting
date: 2019/08/12
description: Modifications to a config that will serve an adversary's impacts or persistence
detection:
  condition: keywords
  keywords:
  - ip http server
  - ip https server
  - kron policy-list
  - kron occurrence
  - policy-list
  - access-list
  - ip access-group
  - archive maximum
falsepositives:
- Legitimate administrators may run these commands
fields:
- CmdSet
id: 671ffc77-50a7-464f-9e3d-9ea2b493b26b
level: medium
logsource:
  category: accounting
  product: cisco
  service: aaa
modified: 2020/09/02
product: cisco
service: aaa
status: experimental
tags:
- attack.persistence
- attack.impact
- attack.t1490
- attack.t1505
- attack.t1565.002
- attack.t1053
title: Cisco Modify Configuration
