author: Dimitrios Slamaris, @atc_project (fix)
date: 2017/05/15
description: This rule detects a DHCP server error in which a specified Callout DLL
  (in registry) could not be loaded
detection:
  condition: selection
  selection:
    winlog.event_data.Source: Microsoft-Windows-DHCP-Server
    winlog.event_id:
    - 1031
    - 1032
    - 1034
falsepositives:
- Unknown
id: 75edd3fd-7146-48e5-9848-3013d7f0282c
level: critical
logsource:
  product: windows
  service: system
modified: 2019/07/17
product: windows
references:
- https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
- https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
- https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
service: system
status: experimental
tags:
- attack.defense_evasion
- attack.t1574.002
title: DHCP Server Error Failed Loading the CallOut DLL
